'use strict';

/**
 * Factura brand rasters (1-bit ESC/POS GS v 0). Generated — see scratchpad gen-logo.py.
 *  • DATA    : the "X." distressed mark (272x170), centered atop the factura.
 *  • WM_DATA : the "X. Pizza" wordmark in Courier New Bold (272x36) — replaces the
 *              plain-text brand header line so it prints in a typewriter face.
 * Widths are byte-aligned; bit 1 = black dot, MSB-first row-major.
 */

const WIDTH = 272;
const HEIGHT = 170;
const DATA = Buffer.from(
  'AAAwAAAAAAAAA/AAAAAAPgAAAAAAAAAhgAAAAAAAAAAAAAAH+P84AAAAH///gAAAA///4AAAAAD/P/gAAAAAAAAAAAAAN/j/v/wH' +
  '/////+AAAA//////gAf/+5/+AAAAAAAAAAAAAHf5/7//f//////wAAAf////////v/Hf/wAAAAAAAAAAAADj8f8//z//////+AAA' +
  'P/////8D/4fwz/+AAAAAAAAAAAAB4fHmP/9f//////wAAH/////+AH8D4O//wAAAAAAAAAAAA/j77n/HT//Af//8AAB//////AA+' +
  'A+BjD8AAAAAAAAAAAAP8w+5/10s/4D///gAAf////70A/nfmZg+AAAAAAAAAAAAD+OfOf/4Jm/////4AAP////+5xn//5v//wAAA' +
  'AAAAAAAAA///7v//D9n////+AAD/////+8f//+b//8AAAAAAAAAAAAP////////8/////gAA///////H///8///gAAAAAAAAAAAD' +
  '//////////////4AAP//////w/z/+P//4AAAAAAAAAAAA//////////////+AAD//////+Dz/8B//+AAAAAAAAAAAAP/////////' +
  '/////gAA///////jB/PAA//gAAAAAAAAAAAD/////////////44AAP//////8w/z4H//4AAAAAAAAAAAA/////////+f//8OAAB/' +
  '/////+If8+P//+AAAAAAAAAAAAP/////////D///DAAAf//////n/nADAf/AAAAAAAAAAAAB/////////wB+H8wAAD////n/5//8' +
  '+AP/wAAAAAAAAAAAAf////////4AH7/4AAA///////////gD/4AAAAAAAAAAAAD////9////AB//8AAAH////+H+///AB/8AAAAA' +
  'AAAAAAAAP8+AGB//fwAP/8AAAAf/4P/h/n/8AA/4AAAAAAAAAAAAAAGIAAAH938AA/8AAAAB/gD3+f8/4AAP8AAAAAAAAAAAAAAA' +
  'AAAAAAM8AAAAAAAAAAAB8///v4AAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAA/3//98AAAAAAAAAAAAAAAAAAAAAAAAAABAA' +
  'AAAAAAAAAAP/hz6cAAAAAAAAAAAAAAAAAAAAAAAAH4IAAAAAAAAAAAAH/4c8mAAAAAAAAAAAAAAAAAAAAAAAAB/HwwOAAAAAAAAA' +
  'D/8/PZAAAAAAAAAAAAAAAAAAAAAAAAAP9/8HwAAAAAAAAB///3/gAAAAAAAAAAAAAAAAAAAAAAAAD///D4AAAAAAAAA/////wAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAf//g8AAAAAAAAAf////4AAAAAAAAAAAAAAAAAAAAAAAAAD//8PAAAAAAAAAH////8AAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAb//n/wAAAAAAAD////+AAAAAAAAAAAAAAAAAAAAAAAAAAA////+AAAAAAAB/////AAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAf////gAAAAAAA//v/4AAAAAAAAAAAAAAAAAAAAAAAAAAAD//A/8AAAAAAAf/5/+AAAAAAAAAAAAAAAAAAAAAAAAAAAA//wf/' +
  'gAAAAAAP/+PBwAAAAAAAAAAAAAAAAAAAAAAAAAAAH/8P/8AAAAAAD//xgMAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8B//gAAAAAB//' +
  '8A/AAAAAAAAAAAAAAAAAAAAAAAAAAAAH+AH/8AAAAAA//+YfgAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wMP/AAAAAAf//3fwAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAH//n74AAAAAP////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAB//h+/AAAAAH////8AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAP4Af/4AAAAD////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AH//AAAAA/////AAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAPgB//wAAAAf////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Af/+AAAAP////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/j//' +
  'wAAAH////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/w//+AAAD////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwP//wAAB/////' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4B//8AAAf////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeB///gAAP////wAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAD////8AAH////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf9///gAD////8AAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAP//8AB/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///gA/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAB//54Af////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///AH////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///' +
  '4D///58AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////B///++AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///4/////AAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///+f////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////4AAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAf////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH////////+AAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAA+f///////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAD////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////' +
  '///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////gAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf//9///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//8D//4AAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAx//O//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///v/+AAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAA///7YwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//MA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/4AgAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gM4HAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPv+D/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3/w/+eAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAD//8P//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///j//+AAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAA///4///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//+P//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAH///n///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///5///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///f//' +
  '/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///z///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB///4f///gAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/P+D///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/x/gf///gAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAB/8/4H///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/H8B/f//AAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAH/x/Af///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/8fwP///5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'Af/D4D///+YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wMB/+QfGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/8CAP/my' +
  'DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAGJ8h4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAD/I/gAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAB/8AAAA//P8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe/gAAAP///wAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAH/4AAAH///+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/+AAAf////wAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAf/gAAD////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAf////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAB' +
  '/4AAAH////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAf+AAAA/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAH/AAAAH///' +
  '/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAzgAAAA/////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAABwAAAAH////4AAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAHAAAB4AAAAA///f+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/wD/8AAAAAP//34AAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAB//A//AAAAAB////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfjwPHgAAAAAP///9wAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAPgABgAAAAAAB////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAH4ABzgAAAAAAP////wAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAf8A' +
  'AAAAAB////+AAAAAAAAAAAAAAAAAAAAAAAAAAAB/wAB+AAAAAAAP////wAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAPAAAAAAAD///' +
  '/+AAAAAAAAAAAAAAAAAAAAAAAAAAAf/wA3wAAAAAAAf////wAAAAAAAAAAAAAAAAAAAAAAAAAAH//g54AAAAAAAD////+AAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAD///88AAAAAAAAf////wAAAAAAAAAAAAAAAAAAAAAAAAAB////+AAAAAAAAD////8AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAA/////AAAAAAAAAf////gAAAAAAAAAAAAAAQAAAAAAAAAAf////gAAAAAAAAD////8AAAAAAAAAAAAAB+fAAAAAAAAA' +
  'Pn///wAAAAAAAAA/////gAAAAAAAAAAAAD//+AAAAAAAADx///4AAAAAAAAAH////8AAAAAAAAAAAAB///wAAAAAAAA////+AAAA' +
  'AAAAAA/////gAAAAAAAAAAAB////AAAAAAABv///8AAAAAAAAAAH////4AAAAAAAAAAAA////4AAAAAAA7////AAAAAAAAAAA///' +
  '//AAAAAAAAAAAAf////AAAAAAAe////wAAAAAAAAAAH////4AAAAAAAAAAAP////4AAAAAAPP///AAAAAAAAAAAB/////AAAAAAA' +
  'AAAAH/////AAAAAAHwf/wAAAAAAAAAAAAP////4AAAAAAAAAAB/////wAAAAAD4Dj4AAAAAAAAAAAAB/////AAAAAAAAAAA/////' +
  '4AAAAAB+A8+AAAAAAAAAAAAAO////4AAAAAAAAAAf////8AAAAAA/wPvwAAAAAAAAAAAABn////AAAAAAAAAAH//3//AAAAAAf8D' +
  '/cIAAAAAAAAAAAAf////4AAAAAAAAAB//5//wAAAAAP/A/3GAAAAAAAAAAAAD//5//AAAAAAAAAA//uW/8AAAAAD/wP95AADwAAA' +
  'AAAAAA//29D4AAMAAAAAAP/78nnCA//A4/8H/+QAB/4AAAAP/4gf/48B8AP/nAAAAAD/+fBxxg/n4OP/D//kAA//AAAAP/4H//+e' +
  'A/gf/98AAAAA//34AEYP//zz/w//7AAP/wAAAH/+H///v//8H///gAAAAf///+BvH///+/8f/+wAD/5gAAD//////////j///4AA' +
  'AAH//////z//////n//OAB/8cAAB//////////8////AAAAB//////x////3/5//zgAP+HAAAf//////////P///wAAAAf/////4' +
  'f///w/+f+84AD/g4AAH//z///////w///+AAAAD/////+H///+P/j/vuAA/4OAAD///v///n//8H//zgAAAAf//P//jn57/n/4/7' +
  '/gAH+DgAA///5/v/h///h///4AAAAH/////448Gb83+Pz/4AB3B4AAP////5/z+P/4f//+AAAAB/////+OA937LPjm/+AA8AfAAD' +
  '/////f//j//H///gAAAAP/////5Yf/+Tx4z//gAP8DgAAf///fz/+A7z8///4AAAAD/////+Tj//gfGJ//4AD/g4AAH///z8//4M' +
  '4GOf/+AAAAA4/////G+/34H5H/H+AA/4OAAB///8/fA+TeZBJ/+AAAAAEH/7/dx//9+P/5/w3gAP+PgAAf////3w/v33xn//gAAA' +
  'ADf/+//cf//f3//f///AD/n4AAH////78/7//8///4AAAAA///v/mD//z8//////wAf58AAA////+/ff///P//+AAAAAH////5Af' +
  '///n/////8AH++AAAP////P/3///7///gAAAAB/////wD//74//////AB/vAAAB////z/9///////wAAAAAP////4Af//+HwAAH7' +
  'gAf5gAAAH/v/8/AAAD////wAAAAAB////8AA///gAAAAAAAH+AAAAAP7/4AAAAAAD//wAAAAAAP///+AAAAAAAAAAAAAAAAAAAAA' +
  'EQAAAAAAAAAMAAAAAAAB////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAA///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAD+AAA=' +
  '', 'base64');

const WM_WIDTH = 272;
const WM_HEIGHT = 36;
const WM_DATA = Buffer.from(
  'AAAAAAAAAAAAAAAAAAAAAAAAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAA/+Af+AAAA' +
  'AAAAAAAAP//8AAAP4AAAAAAAAAAAAAAAAAAAf/wP/wAAAAAAAAAAAH///4AAD+AAAAAAAAAAAAAAAAAAAH/8D/8AAAAAAAAAAAB/' +
  '///AAA/gAAAAAAAAAAAAAAAAAAB//A//AAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAAAAAAAAP/gP/gAAAAAAAAAAAD////AAAAAA' +
  'AAAAAAAAAAAAAAAAAAfwA/gAAAAAAAAAAAAD8Af4AAAAAAAAAAAAAAAAAAAAAAAD+AfwAAAAAAAAAAAAA/AB+AAAAAAAAAAAAAAA' +
  'AAAAAAAAA/wP4AAAAAAAAAAAAAPwAPwAAAAAAAAAAAAAAAAAAAAAAAH8H8AAAAAAAAAAAAAD8AD8AAAAAAAAAAAAAAAAAAA/4AAA' +
  '/j/AAAAAAAAAAAAAA/AAfAH/8AAB///+AH///4AD//gAAH8/gAAAAAAAAAAAAAPwAHwD//AAAf///gB///+AD//+AAA//wAAAAAA' +
  'AAAAAAAD8AB8A//wAAH///4Af///gB///wAAP/4AAAAAAAAAAAAAA/AA/AP/8AAB///+AH///4Af//8AAB/+AAAAAAAAAAAAAAPw' +
  'APwB//AAAf///AB///8AD+A/gAAP/AAAAAAAAAAAAAAD8AH8AAPwAAH4B/wAfgH/AA8AH4AAB/gAAAAAAAAAAAAAA/AD+AAD8AAB' +
  '+A/4AH4D/gAAAA+AAAf4AAAAAAAAAAAAAAPwD/gAA/AAAfgf4AB+B/gAAAAPgAAP/AAAAAAAAAAAAAAD///wAAPwAAD4P8AAPg/w' +
  'AAAAD4AAH/wAAAAAAAAAAAAAA///4AAD8AAA8H+AADwf4AAAf/+AAB/+AAAAAAAAAAAAAAP//4AAA/AAAAD/AAAAP8AAA///gAA/' +
  '/wAAAAAAAAAAAAAD//8AAAPwAAAB/gAAAH+AAAf//4AAf3+AAAAAAAAAAAAAA//4AAAD8AAAA/wAAAD/AAAf//+AAP8/gAAAAAAA' +
  'AAAAAAPwAAAAA/AAAAf4AAAB/gAAP///gAH+H8AAAAAAAAAAAAAD8AAAAAPwAAAP8AAAA/wAAD/AH4AB/A/gAAAAAAAAAAAAA/AA' +
  'AAAD8AAAH+AcAAf4BwB/AA+AA/gH8AAAAAAAAAAAAAPwAAAAA/AAAD/APgAP8A+AfgAPgAfwB/gAAAAAAAAAAAAD8AAAAAPwAAB/' +
  'gD4AH+APgPwAH4AP8AP4AAB4AAAAAAAAA/AAAAAD8AAA/wA+AD/AD4B8AH+AP/gP/wAB/AAAAAAAAD//8AAH///4Af///gB///+A' +
  'fwP/+H/8H/+AAf4AAAAAAAB///gAD////AH///4Af///gH////x//B//gAH+AAAAAAAAf//4AB////wB///+AH///4A//+/8f/wf' +
  '/4AB/gAAAAAAAH//+AAP///8Af///gB///+AH//P/D/4D/8AAfwAAAAAAAA///AAB///+AH///4Af///gA//D/gAAAAAAAB4AAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAA' +
  '', 'base64');

// GS v 0 raster image (m=0). wPx must be byte-aligned.
function gsv0(wPx, hPx, data) {
  const wb = wPx >> 3;
  return Buffer.concat([
    Buffer.from([0x1d, 0x76, 0x30, 0x00, wb & 0xff, (wb >> 8) & 0xff, hPx & 0xff, (hPx >> 8) & 0xff]),
    data,
  ]);
}

// The "X." mark, centered, + 1 blank line below.
function logoBytes() {
  return Buffer.concat([
    Buffer.from([0x1b, 0x61, 0x01]),      // ESC a 1 — center
    gsv0(WIDTH, HEIGHT, DATA),
    Buffer.from([0x1b, 0x61, 0x00]),      // ESC a 0 — left
    Buffer.from([0x0a, 0x0a]),            // image line-close + 1 blank line
  ]);
}

// The "X. Pizza" typewriter wordmark — centered; replaces the plain-text brand header.
function wordmarkBytes() {
  return Buffer.concat([
    Buffer.from([0x1b, 0x61, 0x01]),
    gsv0(WM_WIDTH, WM_HEIGHT, WM_DATA),
    Buffer.from([0x1b, 0x61, 0x00]),
    Buffer.from([0x0a]),
  ]);
}

module.exports = { WIDTH, HEIGHT, DATA, logoBytes, WM_WIDTH, WM_HEIGHT, WM_DATA, wordmarkBytes };
